'use strict';
SH.Battle = class {
 constructor(game,enemyIds){this.g=game;this.enemies=enemyIds.map((id,i)=>({...SH.DATA.enemies[id],id,hp:SH.DATA.enemies[id].hp,maxHp:SH.DATA.enemies[id].hp,index:i}));this.turn='player';this.menu=0;this.message='Monsters appeared!';this.done=false;this.guard=false;this.boss=this.enemies.some(e=>e.boss)}
 alive(){return this.enemies.filter(e=>e.hp>0)}
 command(cmd){if(this.done||this.turn!=='player')return;const p=this.g.s.player;if(p.hp<=0)return;if(cmd==='Attack'){const e=this.alive()[0];if(e)this.hit(e,false)}else if(cmd==='Magic'){if(p.mp<5){this.message='Not enough MP.';return}p.mp-=5;const e=this.alive()[0];if(e)this.hit(e,true)}else if(cmd==='Item'){if((this.g.s.inventory.potion||0)<1){this.message='No Potions.';return}this.g.s.inventory.potion--;p.hp=Math.min(p.maxHp,p.hp+60);this.message='Potion restores 60 HP.';this.afterPlayer()}else if(cmd==='Defend'){this.guard=true;this.message='Kael braces for impact.';this.afterPlayer()}else if(cmd==='Flee'){if(this.boss){this.message='There is no escape!';return}if(Math.random()<.68){this.done=true;this.g.endBattle(false,true);return}else{this.message='Could not escape!';this.afterPlayer()}}}
 hit(e,magic){const p=this.g.s.player,st=this.g.stats();let dmg;if(magic){dmg=Math.max(3,Math.floor((p.magic*2+42)*(e.weak==='fire'?1.5:1)-e.def*.4+Math.random()*7));this.message=`Fire scorches ${e.name} for ${dmg}!`}else{const crit=Math.random()<(.06+p.luck*.002);dmg=Math.max(1,Math.floor((st.attack*1.65-e.def*.75)*(crit?1.65:1)*(0.9+Math.random()*.2)));this.message=`Kael hits ${e.name} for ${dmg}${crit?' — CRITICAL!':''}`};e.hp=Math.max(0,e.hp-dmg);if(!this.alive().length){this.victory();return}this.afterPlayer()}
 afterPlayer(){this.turn='enemy';setTimeout(()=>this.enemyTurn(),380)}
 enemyTurn(){if(this.done)return;const p=this.g.s.player;for(const e of this.alive()){let dmg=Math.max(1,Math.floor((e.str*1.4-this.g.stats().defense*.55)*(0.9+Math.random()*.2)));if(this.guard)dmg=Math.floor(dmg*.5);p.hp=Math.max(0,p.hp-dmg);this.message=`${e.name} attacks for ${dmg}!`;if(p.hp<=0){this.done=true;this.g.gameOver();return}}this.guard=false;this.turn='player'}
 victory(){this.done=true;let xp=0,jp=0,gold=0,drops=[];for(const e of this.enemies){xp+=e.xp;jp+=e.jp;gold+=Math.floor(e.gold[0]+Math.random()*(e.gold[1]-e.gold[0]+1));if(e.drop&&Math.random()<e.drop[1])drops.push(e.drop[0])}for(const id of drops)this.g.addItem(id,1);this.g.gainRewards(xp,jp,gold,drops);this.message=`VICTORY! +${xp} XP  +${jp} JP  +${gold} Gold`;setTimeout(()=>this.g.endBattle(true,false),900)}
};