'use strict';
window.SH = window.SH || {};
SH.DATA = {
 items:{potion:{name:'Potion',type:'consumable',price:25,desc:'Restores 60 HP.',heal:60},hiPotion:{name:'Hi-Potion',type:'consumable',price:120,desc:'Restores 180 HP.',heal:180},antidote:{name:'Antidote',type:'consumable',price:18,desc:'Cures poison.'},echo:{name:'Echo Herb',type:'consumable',price:24,desc:'Cures silence.'},phoenix:{name:'Phoenix Feather',type:'consumable',price:180,desc:'Revives an ally.',revive:80},tent:{name:'Tent',type:'consumable',price:150,desc:'Restores the party at a save point.'},fang:{name:'Goblin Fang',type:'material',price:8,desc:'A chipped monster fang.'},fragment:{name:'Ancient Star Fragment',type:'key',price:0,desc:'A warm shard that pulses like a distant star.'}},
 weapons:{oldSword:{name:'Old Sword',slot:'weapon',price:0,atk:5,desc:'A worn family blade.'},bronzeSword:{name:'Bronze Sword',slot:'weapon',price:90,atk:10,desc:'Reliable bronze steel.'},ironSword:{name:'Iron Sword',slot:'weapon',price:190,atk:17,desc:'A sturdy forged blade.'},dagger:{name:'Dagger',slot:'weapon',price:70,atk:7,agi:2,desc:'Light and quick.'}},
 armor:{traveler:{name:"Traveler's Shirt",slot:'body',price:0,def:3},leatherVest:{name:'Leather Vest',slot:'body',price:80,def:7},ironMail:{name:'Iron Mail',slot:'body',price:210,def:14,agi:-1},leatherCap:{name:'Leather Cap',slot:'head',price:55,def:4},woodShield:{name:'Wooden Shield',slot:'shield',price:65,def:5},boots:{name:'Leather Boots',slot:'accessory',price:0,def:1,agi:1},poisonWard:{name:'Poison Ward',slot:'accessory',price:150,def:1,poisonImmune:true}},
 spells:{cure:{name:'Cure',mp:4,power:55,target:'ally'},fire:{name:'Fire',mp:5,power:42,element:'fire',target:'enemy'}},
 jobs:{wanderer:{name:'Wanderer',abilities:[['Focus',40],['Trail Sense',90],['Second Wind',180]]},warrior:{name:'Warrior',abilities:[['Power Strike',45],['Counter',130],['Last Stand',300]]},whiteMage:{name:'White Mage',abilities:[['White Magic I',50],['Mend',140],['Blessing',320]]},blackMage:{name:'Black Mage',abilities:[['Black Magic I',50],['Arcane Focus',140],['Elemental Lore',320]]}},
 enemies:{slime:{name:'Slime',hp:42,str:7,def:2,agi:5,xp:12,jp:3,gold:[6,10],weak:'fire',color:'#6bbf9b',drop:['potion',.08]},wolf:{name:'Grey Wolf',hp:68,str:12,def:4,agi:10,xp:20,jp:4,gold:[9,15],color:'#9b9aa6'},goblin:{name:'Goblin',hp:76,str:13,def:5,agi:7,xp:24,jp:5,gold:[10,16],color:'#7d9f54',drop:['fang',.22]},hornet:{name:'Gloom Hornet',hp:48,str:10,def:3,agi:13,xp:18,jp:4,gold:[7,13],color:'#d9a43b'},silverSlime:{name:'Silver Slime',hp:36,str:8,def:18,agi:16,xp:120,jp:35,gold:[45,60],color:'#b8d9e8',rare:true},bat:{name:'Cave Bat',hp:55,str:10,def:3,agi:12,xp:18,jp:4,gold:[7,12],color:'#6f5b83'},toad:{name:'Poison Toad',hp:88,str:13,def:6,agi:5,xp:27,jp:6,gold:[12,18],color:'#668f4f'},stoneback:{name:'STONEBACK',hp:460,str:22,def:11,agi:6,xp:260,jp:85,gold:[150,150],color:'#8b7960',boss:true}},
 shops:{item:['potion','antidote','echo','phoenix','tent'],weapon:['bronzeSword','ironSword','dagger'],armor:['leatherVest','ironMail','leatherCap','woodShield','poisonWard']},
 quests:{main:{name:'A Quiet Morning',text:'Visit Elder Rowan near the northern hill.'},necklace:{name:'Lost Necklace',text:'Find Lysa’s necklace by the river.'},herbs:{name:'Herbs for Mara',text:'Bring Mara 2 Goblin Fangs.'}}
};