'use strict';
(()=>{
const C=document.getElementById('game'),c=C.getContext('2d');c.imageSmoothingEnabled=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y), fmt=t=>`${String(Math.floor(t/3600)).padStart(2,'0')}:${String(Math.floor(t%3600/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
class Game{
 constructor(){this.mode='title';this.titleIndex=0;this.keys={};this.last=performance.now();this.acc=0;this.s=null;this.battle=null;this.dialog=null;this.menu=null;this.shop=null;this.notice='';this.noticeT=0;this.bind();requestAnimationFrame(t=>this.loop(t))}
 fresh(){return {saveVersion:1,map:'home',x:5,y:5,playtime:0,player:{name:'Kael',level:1,xp:0,nextXp:55,hp:100,maxHp:100,mp:24,maxMp:24,str:10,vit:9,magic:8,spirit:8,agi:9,luck:7,job:'wanderer',jobLevel:1,jp:0,nextJp:80,equipment:{weapon:'oldSword',shield:null,head:null,body:'traveler',accessory:'boots'},abilities:[]},inventory:{potion:3,antidote:1},equipment:{},gold:50,quests:{main:'active',necklace:'available',herbs:'available'},flags:{metElder:false,leftTown:false,enteredCave:false,defeatedStoneback:false,necklaceFound:false,necklaceDone:false,herbsDone:false},opened:{},bestiary:{},settings:{battleMode:'WAIT',shake:true},encounterMeter:0,autosaveUnlocked:false}}
 bind(){addEventListener('keydown',e=>{const m={ArrowUp:'up',KeyW:'up',ArrowDown:'down',KeyS:'down',ArrowLeft:'left',KeyA:'left',ArrowRight:'right',KeyD:'right',Enter:'confirm',KeyZ:'confirm',Escape:'cancel',KeyX:'cancel',KeyM:'menu'};if(m[e.code]){e.preventDefault();this.input(m[e.code],true)}});addEventListener('keyup',e=>{});document.querySelectorAll('[data-action]').forEach(b=>{const a=b.dataset.action;const f=e=>{e.preventDefault();this.input(a,true)};b.addEventListener('pointerdown',f)})}
 input(a){if(this.mode==='title'){if(a==='up'||a==='down')this.titleIndex=(this.titleIndex+(a==='up'?3:1))%4;if(a==='confirm')this.titleChoose();return}if(this.mode==='battle'){if(a==='up')this.battle.menu=(this.battle.menu+4)%5;if(a==='down')this.battle.menu=(this.battle.menu+1)%5;if(a==='confirm')this.battle.command(['Attack','Magic','Item','Defend','Flee'][this.battle.menu]);return}if(this.dialog){if(a==='confirm'||a==='cancel')this.dialog=null;return}if(this.menu){this.menuInput(a);return}if(this.shop){this.shopInput(a);return}if(a==='menu'){this.openMenu();return}if(a==='confirm'){this.interact();return}if(['up','down','left','right'].includes(a))this.move(a)}
 titleChoose(){if(this.titleIndex===0){this.s=this.fresh();this.mode='world';this.dialog='Morning light spills through the window. Mother calls from downstairs: “Kael! Elder Rowan asked for you!”'}else if(this.titleIndex===1||this.titleIndex===2){const sm=SH.Save.summaries().find(x=>!x.empty);if(sm){this.s=SH.Save.read(sm.slot);this.mode='world';this.notice=`Loaded ${sm.slot==='auto'?'Auto Save':'Slot '+sm.slot}`;this.noticeT=2}else this.notice='No save data found.'}else this.notice='Settings are available from the in-game menu.'}
 stats(){const p=this.s.player,D=SH.DATA;let atk=p.str,def=p.vit,agi=p.agi;for(const id of Object.values(p.equipment)){if(!id)continue;const q=D.weapons[id]||D.armor[id]||{};atk+=q.atk||0;def+=q.def||0;agi+=q.agi||0}return {attack:atk,defense:def,agi}}
 move(a){const d={up:[0,-1],down:[0,1],left:[-1,0],right:[1,0]}[a],m=SH.MAPS[this.s.map];let nx=clamp(this.s.x+d[0],1,m.w-2),ny=clamp(this.s.y+d[1],1,m.h-2);if((m.solids||[]).some(r=>nx>=r.x&&nx<r.x+r.w&&ny>=r.y&&ny<r.y+r.h))return;this.s.x=nx;this.s.y=ny;for(const w of m.warps||[])if(nx>=w.x&&nx<w.x+w.w&&ny>=w.y&&ny<w.y+w.h){if(w.locked&&!this.s.flags.defeatedStoneback)continue;this.warp(w);return}if(!m.safe){this.s.encounterMeter+=8+Math.random()*8;if(this.s.encounterMeter>100){this.s.encounterMeter=-45;this.startEncounter()}}}
 warp(w){this.s.map=w.to;this.s.x=w.tx;this.s.y=w.ty;if(w.to==='world')this.s.flags.leftTown=true;if(w.to==='cave')this.s.flags.enteredCave=true;if(this.s.autosaveUnlocked)SH.Save.autosave(this.s);this.notice=SH.MAPS[w.to].name;this.noticeT=1.5}
 interact(){const m=SH.MAPS[this.s.map],near=(m.objects||[]).filter(o=>Math.hypot(o.x-this.s.x,o.y-this.s.y)<=2.2).sort((a,b)=>dist(a,this.s)-dist(b,this.s))[0];if(!near){this.notice='Nothing interesting nearby.';this.noticeT=1;return}if(near.text)this.dialog=near.text;else if(near.chest)this.chest(near);else if(near.shop)this.openShop(near.shop);else if(near.inn)this.inn();else if(near.npc)this.npc(near.npc)}
 chest(o){if(this.s.opened[o.chest]){this.dialog='The chest is empty.';return}this.s.opened[o.chest]=true;this.addItem(o.item,1);this.dialog=`Found ${SH.DATA.items[o.item]?.name||o.item} ×1!`}
 npc(id){if(id==='elder'){if(!this.s.flags.metElder){this.s.flags.metElder=true;this.s.autosaveUnlocked=true;this.s.quests.main='cave';this.dialog='Elder Rowan: “Whisperwood has gone silent. Take this charm and investigate the cave northwest of the village.”';SH.Save.autosave(this.s)}else if(this.s.flags.defeatedStoneback){this.s.quests.main='complete';this.dialog='Elder Rowan: “That fragment… I have seen its star-mark only once. We must learn what woke beneath Whisperwood.”'}else this.dialog='Elder Rowan: “The cave lies northwest across the vale. Be careful, Kael.”'}
 else if(id==='lysa'){if(this.s.flags.necklaceDone)this.dialog='Lysa: “I still can’t believe you found it. Thank you!”';else if(this.s.flags.necklaceFound){this.s.flags.necklaceDone=true;this.s.gold+=75;this.gainXP(20);this.dialog='Lysa: “My necklace! You found it! Please take 75 Gold.”'}else{this.s.quests.necklace='active';this.dialog='Lysa: “I lost Mother’s necklace near the river. Would you look for it?”'}}
 else if(id==='necklace'){if(!this.s.flags.necklaceFound){this.s.flags.necklaceFound=true;this.dialog='You find a small silver necklace caught in the reeds.'}else this.dialog='Only river grass remains here.'}
 else if(id==='mara'){if(this.s.flags.herbsDone)this.dialog='Mara: “The tonic worked beautifully.”';else if((this.s.inventory.fang||0)>=2){this.s.inventory.fang-=2;this.s.flags.herbsDone=true;this.s.gold+=90;this.gainXP(25);this.dialog='Mara: “Perfect. These fangs make a potent tonic. Take 90 Gold.”'}else{this.s.quests.herbs='active';this.dialog='Mara: “Bring me two Goblin Fangs and I’ll pay well.”'}}
 else if(id==='spring'){this.s.player.hp=this.s.player.maxHp;this.s.player.mp=this.s.player.maxMp;this.dialog='The clear spring restores HP and MP.'}
 else if(id==='savepoint'){SH.Save.write('1',this.s);this.dialog='Your journey has been saved to Slot 1.'}
 else if(id==='boss'){if(this.s.flags.defeatedStoneback)this.dialog='Only broken stone remains.';else this.startBattle(['stoneback'])}}
 inn(){if(this.s.gold<20){this.dialog='Innkeeper: “A room is 20 Gold. Come back when you have enough.”';return}this.s.gold-=20;this.s.player.hp=this.s.player.maxHp;this.s.player.mp=this.s.player.maxMp;SH.Save.autosave(this.s);this.dialog='You rest until morning. HP and MP fully restored.'}
 openShop(type){this.shop={type,index:0};}
 shopInput(a){const list=SH.DATA.shops[this.shop.type];if(a==='cancel'){this.shop=null;return}if(a==='up')this.shop.index=(this.shop.index+list.length-1)%list.length;if(a==='down')this.shop.index=(this.shop.index+1)%list.length;if(a==='confirm'){const id=list[this.shop.index],obj=SH.DATA.items[id]||SH.DATA.weapons[id]||SH.DATA.armor[id];if(this.s.gold<obj.price){this.notice='Not enough Gold.';this.noticeT=1;return}this.s.gold-=obj.price;if(SH.DATA.items[id])this.addItem(id,1);else this.s.equipment[id]=(this.s.equipment[id]||0)+1;this.notice=`Bought ${obj.name}`;this.noticeT=1}}
 openMenu(){this.menu={page:'root',index:0};}
 menuInput(a){if(a==='cancel'){if(this.menu.page==='root')this.menu=null;else{this.menu.page='root';this.menu.index=0}return}const root=['Items','Equipment','Status','Jobs','Quests','Bestiary','Save','Close'];if(this.menu.page==='root'){if(a==='up')this.menu.index=(this.menu.index+root.length-1)%root.length;if(a==='down')this.menu.index=(this.menu.index+1)%root.length;if(a==='confirm'){const k=root[this.menu.index];if(k==='Close')this.menu=null;else if(k==='Save'){SH.Save.write('1',this.s);this.notice='Saved to Slot 1';this.noticeT=1.4}else{this.menu.page=k.toLowerCase();this.menu.index=0}}}else if(this.menu.page==='items'){if(a==='confirm'&&(this.s.inventory.potion||0)>0&&this.s.player.hp<this.s.player.maxHp){this.s.inventory.potion--;this.s.player.hp=Math.min(this.s.player.maxHp,this.s.player.hp+60)}}else if(this.menu.page==='equipment'){const choices=Object.keys(this.s.equipment).filter(k=>this.s.equipment[k]>0);if(a==='up'&&choices.length)this.menu.index=(this.menu.index+choices.length-1)%choices.length;if(a==='down'&&choices.length)this.menu.index=(this.menu.index+1)%choices.length;if(a==='confirm'&&choices.length){const id=choices[this.menu.index],obj=SH.DATA.weapons[id]||SH.DATA.armor[id];this.s.player.equipment[obj.slot]=id;this.notice=`Equipped ${obj.name}`;this.noticeT=1}}
 }
 startEncounter(){const table=SH.ENCOUNTERS[SH.MAPS[this.s.map].encounters],r=Math.random();let group=table[Math.floor(Math.random()*Math.min(table.length,r>.94?table.length:table.length-1))];this.startBattle(group)}
 startBattle(ids){this.mode='battle';for(const id of ids)this.s.bestiary[id]=(this.s.bestiary[id]||0)+1;this.battle=new SH.Battle(this,ids)}
 endBattle(win,fled){if(win&&this.battle?.boss){this.s.flags.defeatedStoneback=true;this.addItem('fragment',1);this.s.quests.main='return';SH.Save.autosave(this.s);this.dialog='The Ancient Star Fragment hums in Kael’s hand. For an instant, the cave ceiling looks like a sky full of unfamiliar stars.'}this.mode='world';this.battle=null;if(fled){this.notice='Escaped safely.';this.noticeT=1}}
 gameOver(){this.mode='gameover'}
 gainRewards(xp,jp,gold,drops){this.s.gold+=gold;this.gainXP(xp);this.gainJP(jp);if(drops.length)this.notice='Drop: '+drops.map(x=>SH.DATA.items[x]?.name||x).join(', '),this.noticeT=2}
 gainXP(x){const p=this.s.player;p.xp+=x;while(p.xp>=p.nextXp){p.xp-=p.nextXp;p.level++;p.nextXp=Math.floor(p.nextXp*1.28+20);p.maxHp+=14+p.vit;p.maxMp+=3;p.str+=2;p.vit++;p.agi++;p.hp=p.maxHp;p.mp=p.maxMp;this.notice=`LEVEL UP! Kael reached Lv ${p.level}`;this.noticeT=2}}
 gainJP(x){const p=this.s.player;p.jp+=x;while(p.jp>=p.nextJp){p.jp-=p.nextJp;p.jobLevel++;p.nextJp=Math.floor(p.nextJp*1.45);this.notice=`JOB LEVEL UP! ${SH.DATA.jobs[p.job].name} Lv ${p.jobLevel}`;this.noticeT=2}}
 addItem(id,n){this.s.inventory[id]=(this.s.inventory[id]||0)+n}
 loop(t){let dt=Math.min(.05,(t-this.last)/1000);this.last=t;if(this.s&&this.mode!=='title')this.s.playtime+=dt;if(this.noticeT>0)this.noticeT-=dt;this.draw();requestAnimationFrame(x=>this.loop(x))}
 draw(){c.clearRect(0,0,C.width,C.height);if(this.mode==='title')return this.drawTitle();if(this.mode==='battle')return this.drawBattle();if(this.mode==='gameover')return this.drawGameOver();this.drawWorld();if(this.shop)this.drawShop();else if(this.menu)this.drawMenu();else if(this.dialog)this.drawDialog();if(this.noticeT>0)SH.UI.text(c,this.notice,480,45,20,'#ffe78d','center')}
 drawTitle(){const g=c.createLinearGradient(0,0,0,540);g.addColorStop(0,'#090c28');g.addColorStop(.55,'#3c315f');g.addColorStop(1,'#12111c');c.fillStyle=g;c.fillRect(0,0,960,540);for(let i=0;i<60;i++){c.fillStyle=`rgba(255,245,190,${.25+(i%4)/8})`;c.fillRect((i*149)%960,(i*83)%250,2,2)}c.fillStyle='#141522';c.beginPath();c.moveTo(0,350);for(let x=0;x<=960;x+=80)c.lineTo(x,260+((x*17)%130));c.lineTo(960,540);c.lineTo(0,540);c.fill();SH.UI.text(c,'SAFEHAVEN',480,150,66,'#f1d889','center');SH.UI.text(c,'A 16-Bit Fantasy Adventure',480,185,20,'#cfc4ea','center');const opts=['NEW GAME','CONTINUE','LOAD GAME','SETTINGS'];opts.forEach((o,i)=>SH.UI.text(c,(i===this.titleIndex?'◆ ':'  ')+o,480,300+i*48,23,i===this.titleIndex?'#ffe99b':'#eee6d4','center'));SH.UI.text(c,'Arrow Keys / WASD • Enter/Z • M Menu',480,500,15,'#aaa1bd','center')}
 drawWorld(){const m=SH.MAPS[this.s.map],tw=24,ox=480-this.s.x*tw,oy=270-this.s.y*tw;c.fillStyle=m.bg;c.fillRect(0,0,960,540);for(let y=0;y<m.h;y++)for(let x=0;x<m.w;x++){const sx=ox+x*tw,sy=oy+y*tw;if(sx<-24||sy<-24||sx>960||sy>540)continue;c.fillStyle=((x+y)%2)?'rgba(255,255,255,.025)':'rgba(0,0,0,.025)';c.fillRect(sx,sy,24,24)}for(const o of m.objects||[]){const x=ox+o.x*tw,y=oy+o.y*tw;c.fillStyle=o.npc==='boss'?'#7d695a':o.shop?'#c38b5c':o.inn?'#7c568d':o.chest?'#d0a34e':'#d9d0a4';c.fillRect(x-8,y-12,16,20);if(Math.hypot(o.x-this.s.x,o.y-this.s.y)<4)SH.UI.text(c,o.label,x,y-18,11,'#fff','center')}for(const w of m.warps||[]){const x=ox+w.x*tw,y=oy+w.y*tw;c.strokeStyle='rgba(245,214,113,.35)';c.strokeRect(x,y,w.w*tw,w.h*tw)}c.fillStyle='#ead27d';c.fillRect(472,258,16,22);c.fillStyle='#3c294b';c.fillRect(476,250,8,10);SH.UI.panel(c,12,12,280,76);SH.UI.text(c,m.name,26,38,18,'#e7c66b');SH.UI.text(c,`${this.s.player.name} Lv ${this.s.player.level} • ${this.s.gold} Gold`,26,63,16);SH.UI.bar(c,710,18,220,12,this.s.player.hp,this.s.player.maxHp);SH.UI.text(c,`HP ${this.s.player.hp}/${this.s.player.maxHp}`,710,48,14);SH.UI.text(c,'A: Interact   M: Menu',760,520,14,'#e4dfd2')}
 drawDialog(){SH.UI.panel(c,80,390,800,125);const words=this.dialog.split(' ');let line='',y=425;for(const w of words){if(c.measureText(line+w).width>720){SH.UI.text(c,line,105,y,19);line='';y+=27}line+=w+' '}SH.UI.text(c,line,105,y,19);SH.UI.text(c,'▼',845,490,16,'#e7c66b')}
 drawShop(){const list=SH.DATA.shops[this.shop.type];SH.UI.panel(c,120,70,720,400,`${this.shop.type.toUpperCase()} SHOP — ${this.s.gold} Gold`);list.forEach((id,i)=>{const o=SH.DATA.items[id]||SH.DATA.weapons[id]||SH.DATA.armor[id];SH.UI.text(c,(i===this.shop.index?'◆ ':'  ')+o.name,160,130+i*42,20,i===this.shop.index?'#ffe78d':'#fff3cc');SH.UI.text(c,`${o.price} G`,700,130+i*42,18,'#d9c377','right')});const id=list[this.shop.index],o=SH.DATA.items[id]||SH.DATA.weapons[id]||SH.DATA.armor[id];SH.UI.text(c,o.desc||`${o.slot} equipment`,160,355,17,'#c9bfd8');if(o.atk)SH.UI.text(c,`Attack +${o.atk}`,160,383,16);if(o.def)SH.UI.text(c,`Defense +${o.def}`,160,410,16);SH.UI.text(c,'A Buy • B Leave',160,445,16,'#d9c377')}
 drawMenu(){const p=this.s.player,root=['Items','Equipment','Status','Jobs','Quests','Bestiary','Save','Close'];SH.UI.panel(c,70,45,820,450,'SAFEHAVEN');SH.UI.text(c,`${p.name}  Lv ${p.level}  ${SH.DATA.jobs[p.job].name} Lv ${p.jobLevel}`,105,90,23);SH.UI.bar(c,105,107,250,12,p.hp,p.maxHp);SH.UI.text(c,`HP ${p.hp}/${p.maxHp}   MP ${p.mp}/${p.maxMp}`,105,143,16);SH.UI.text(c,`${this.s.gold} Gold   Play ${fmt(this.s.playtime)}`,600,90,16);if(this.menu.page==='root')root.forEach((x,i)=>SH.UI.text(c,(i===this.menu.index?'◆ ':'  ')+x,120,195+i*34,19,i===this.menu.index?'#ffe78d':'#fff3cc'));else this.drawMenuPage()}
 drawMenuPage(){const p=this.s.player,page=this.menu.page;SH.UI.text(c,page.toUpperCase(),110,185,22,'#e7c66b');if(page==='items'){Object.entries(this.s.inventory).filter(([,n])=>n>0).forEach(([id,n],i)=>SH.UI.text(c,`${SH.DATA.items[id]?.name||id} ×${n}`,130,225+i*28,17));SH.UI.text(c,'A uses Potion when available.',110,455,15,'#b9afc8')}else if(page==='equipment'){const choices=Object.keys(this.s.equipment).filter(k=>this.s.equipment[k]>0);choices.forEach((id,i)=>{const o=SH.DATA.weapons[id]||SH.DATA.armor[id];SH.UI.text(c,(i===this.menu.index?'◆ ':'  ')+`${o.name} ×${this.s.equipment[id]}`,130,225+i*30,17,i===this.menu.index?'#ffe78d':'#fff3cc')});const st=this.stats();SH.UI.text(c,`ATK ${st.attack}   DEF ${st.defense}   AGI ${st.agi}`,520,225,18)}else if(page==='status'){const st=this.stats();[['Level',p.level],['XP',`${p.xp}/${p.nextXp}`],['JP',`${p.jp}/${p.nextJp}`],['Attack',st.attack],['Defense',st.defense],['Magic',p.magic],['Agility',st.agi],['Luck',p.luck]].forEach((q,i)=>SH.UI.text(c,`${q[0]}: ${q[1]}`,130+(i>3?360:0),225+(i%4)*35,18))}else if(page==='jobs'){SH.UI.text(c,`${SH.DATA.jobs[p.job].name} — Job Lv ${p.jobLevel}`,130,230,20);SH.UI.text(c,`JP ${p.jp}/${p.nextJp}`,130,265,18);SH.UI.text(c,'More Jobs awaken through future story relics.',130,315,16,'#b9afc8')}else if(page==='quests'){const q=this.s.quests;SH.UI.text(c,`MAIN: ${q.main==='complete'?'✓ ':''}A Quiet Morning`,130,225,18);SH.UI.text(c,q.main==='return'?'Return to Elder Rowan.':q.main==='cave'?'Investigate Whisperwood Cave.':'Visit Elder Rowan.',150,252,16,'#c8bdd7');SH.UI.text(c,`${this.s.flags.necklaceDone?'✓ ':''}Lost Necklace`,130,300,18);SH.UI.text(c,`${this.s.flags.herbsDone?'✓ ':''}Herbs for Mara`,130,335,18)}else if(page==='bestiary'){Object.keys(this.s.bestiary).forEach((id,i)=>SH.UI.text(c,`${SH.DATA.enemies[id].name} — encountered ${this.s.bestiary[id]}×`,130,225+i*28,17))}}
 drawBattle(){const b=this.battle,p=this.s.player;c.fillStyle=b.boss?'#271d2a':'#263b43';c.fillRect(0,0,960,540);for(let i=0;i<8;i++){c.fillStyle=`rgba(255,255,255,${.02+i*.006})`;c.fillRect(0,280+i*22,960,12)}b.enemies.forEach((e,i)=>{if(e.hp<=0)return;const x=180+(i%3)*120,y=210+Math.floor(i/3)*100;c.fillStyle=e.color;c.beginPath();c.arc(x,y,e.boss?70:38,0,Math.PI*2);c.fill();SH.UI.text(c,e.name,x,y-60,16,'#fff','center');SH.UI.bar(c,x-48,y+50,96,8,e.hp,e.maxHp,'#d76565')});c.fillStyle='#e6d17f';c.fillRect(730,250,38,70);c.fillStyle='#493657';c.fillRect(740,230,20,25);SH.UI.panel(c,40,365,520,145);SH.UI.text(c,b.message,65,400,18);const cmds=['Attack','Magic','Item','Defend','Flee'];cmds.forEach((x,i)=>SH.UI.text(c,(i===b.menu?'◆ ':'  ')+x,65+(i%3)*150,445+Math.floor(i/3)*32,17,i===b.menu?'#ffe78d':'#fff'));SH.UI.panel(c,600,365,320,145,`${p.name} Lv ${p.level}`);SH.UI.text(c,`HP ${p.hp}/${p.maxHp}`,625,418,17);SH.UI.bar(c,625,430,245,10,p.hp,p.maxHp);SH.UI.text(c,`MP ${p.mp}/${p.maxMp}`,625,470,17,'#a9c7ff')}
 drawGameOver(){c.fillStyle='#05050a';c.fillRect(0,0,960,540);SH.UI.text(c,'GAME OVER',480,210,54,'#b94f61','center');SH.UI.text(c,'Press Enter to load Auto Save',480,285,20,'#ddd','center');if(this.keys){} }
 }
 const g=new Game();window.safehaven=g;
 addEventListener('keydown',e=>{if(g.mode==='gameover'&&(e.code==='Enter'||e.code==='KeyZ')){const s=SH.Save.read('auto')||SH.Save.read('1');if(s){g.s=s;g.mode='world'}else{g.mode='title';g.titleIndex=0}}});
})();